# Generated by Django 3.2 on 2023-02-04 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='transaction.courier')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('courier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='transaction.courier', verbose_name='Courier')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('courier', 'date')},
            },
        ),
    ]
